language: java
jdk: oraclejdk8
dist: trusty
script: ant dist
before_install:
  - wget https://github.com/JetBrains/kotlin/releases/download/v1.3.50/kotlin-compiler-1.3.50.zip && unzip kotlin-compiler-1.3.50.zip
deploy:
  provider: releases
  api_key:
    secure: kwypZSpC5CtIDJiUC/V3QUqeXgZylkOmLwoh8Rzw4fJ4XS8gBFCArOuQER5qiQOJIzEa8vFV/iRBek3ENfayyVyHjhB06HSP+bTiyl4vpk1ZdRYVkWxyxIkOrK/6yl0rh3D+rh9y0cvYIsU+GYQ3gcVyv/emoZVQwqqjMKSkrY8wyP0RvGAbzQYSLqT6APBRYb3UZ4W9zgUaONAPaXV8x8jM6R2A9kgVA15tdQs0zyEddxfGZj5iJoraIcmanGA2DRUT3l0EPScToQOJbuuwGwuLjmVOtO1j6aFsrU5aV0msmkub0X9Osh/Y/KLHcOCG95d6qdyvuQHeUkN2e2iA1Csf/ETO/dpZnPawuYhuKTpHZ71f4pBs1aXWlu4eIYzkKpopMNup6MsYZMfqFTp09GXUaJ9Ka0vzLCaXNl/ky+XIjgpl91IZxAJuVLGIEzcUd/TPnJJFmuK+yuJNgtZzgHswigiY/ypgXpEDjZslOorvMJ9YOihzijEHRDzaud/pVj5Tzb5s6Kl9fcR8ceFqH3xcYUQp5hJzy3W2dZXmrKTkTmti+Gyyhd0sw27i24c+Rt42c2QYChYakfRhe+twM9CbeSodI5J2LBA84EwX7T4HLdJuZRriaYP15WG5+ZmUDjJYR0oXm+iC9JzeCYkXTJE5Vf2+i5Y5b7IYtW1MrwY=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    all_branches: true
#The following is required to compile JavaFX	
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
