language: java
jdk: oraclejdk8
dist: trusty
script: ant dist
before_install:
  - wget https://github.com/JetBrains/kotlin/releases/download/v1.3.50/kotlin-compiler-1.3.50.zip && unzip kotlin-compiler-1.3.50.zip
deploy:
  provider: releases
  api_key:
    secure: LVV3OW2jaf+qfXWENqQbKlrG0Oy8xvqbuKIBtqpxcePs5Lg5fDKr8wXnYAqZ8FDh32SveXFsX8mx0pRYxN33AQw8ZNLCmdUN9NPPhkvW8aIm6EZJBUmwTZQCFNuhIyqAoRts635qW6VGqhhHm+kUKz+TM2OubCYZYKSZJPuzKKsFk8hSkfgiV8nH0isWsWRWiEniOH9udAD69qimU5175G/LsK3CO7RtZsvevhdpDuEvCoQD0sSMJxnBZoX92aobRqmE1/pHBgiNhXKMqjC2rwDdQZTUnqto96VaGItm6OG0uwAAD1MtUtqMQc5KSFENz0IpgGry3IpC7AozA3VS6oJFk+V6hkZi/nxme3zAg1pow1cAgoOnvdo5Gw83zokYCqHYSuLBVn7MceYIJyh5U9AE3F1ACns9VLA4sEuypfMxTmQNssoylXK3IAqosIz7c3QvDqaVzb+QU/GuTQ6nqNXSdlUa8IYqf+FsnsJKmA3P90nkte83IF9pA6o226ffVyLFn5dtSLiGpAUpwvfzdVC84saeS+EgvP7m8Wg9LaBB4aTF8RDJ6RE1CWIHg2YaiVD/NeSITIyoNp9gK6pgo6teRE3uklPgLuDhEJBM9b5d95CmGkTrkR+XVasUsvW6Bdls1AexnnBrMT2HWY2kgpZ6f5Hx3fgJUsh3r8GfEn4=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    all_branches: true
#The following is required to compile JavaFX	
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
