language: java
jdk: oraclejdk8
dist: trusty
script: ant dist
before_install:
  - wget https://github.com/JetBrains/kotlin/releases/download/v1.3.50/kotlin-compiler-1.3.50.zip && unzip kotlin-compiler-1.3.50.zip
deploy:
  provider: releases
  api_key:
    secure: "E6x8skzOfyXp3Yf6RBPnfbXtXj92ANCcDiQgB7+TWN4/QBTo67jInl0YnspOb9S0g2IpKvufFHAj1hyuYHrpTjGG6y+L
    4xPdOn6QCKknNsVjq2+RvitmXYtOooNq3msd+KRLb3TOSyuNXUn2zzjXOiqZulgmKAko6vPX4QfvGcyLplo6repGvmB+M9wNuNvZg3C
    Fd+F3XuRCIisuE59ynQHE9YZYHV3gv65+VkSfdsilf6goxutmxwVJceLHOlSIn19SXyBOVq164ey6MoB5tPc3OA56yLriYWB+6JOF+b
    RBEM9Tl8W2xLp14KL3y1Pg8vubjunzblHKKx477byLgnE0ZIZbXbrXcgl83m04yOWH46kNMAStvWC1/HXA++eCZgWcS2FGy0l//HH3D
    CjTEkKrrk1G8M6Xxf6EMikzuGCrSlja1c8kCPBOLXuMvmL8cWinyE9IuoII+qW4WERmxFlguio4aaZ/5q4wSXei/jfSV3XRdv0cw0jL
    1DepK/LAY1i6Dpgi8QnX2uhUktHfLo2WvqZp6U1DwJScBrhC9ubT41ZVBvVItieecG7JULQ94gLCjDL+fcrv86g5g4vU1NdtrHrIaBD
    XZEBjOMuiHjtqeJsJBFVkdHUWxZ0wpLm/YvtcKfU9812ggB9lYfECJEZhTXZ04twommX7h+RQdLY="
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    all_branches: true
#The following is required to compile JavaFX	
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
