language: java
jdk: oraclejdk8
dist: trusty
script: ant dist
before_install:
  - wget https://github.com/JetBrains/kotlin/releases/download/v1.3.50/kotlin-compiler-1.3.50.zip && unzip kotlin-compiler-1.3.50.zip
deploy:
  provider: releases
  api_key:
    secure: Qx5fCJCIinY2lKED8g95pVmCpyKfb8AnaTZRvHXrEKJounEfeI92pLPxw7g0VkrYQTkm+RbDB0PqotJQsOe0jL5LnmLNKJ4WITRqu+GNcVwNXWRXYyuQI4MIdQsI0wUZCIhjvCWiyaUw9tXcL7+Vc8WW+qHmcYuFgbp/Y43TRQDQKclPkgZb+SvVffIe0qXx0HbPFbhBTluxI9+dsdfTiZhF67vUTjFsLe5ZKpcngGNTxIdD7RKLBZOr1RH9glxO/TSdOdM4/RGWpnJNRlcRy6nVguucZcRnaPXEL88So/ZEjcT5oMnfjNX3I5gToqZzo5ly2XY+sUPrbQeRYgeJJnv0FbOWWNMd7g3dXUphX94Nd1dwjayXwXNpAD8YJo1L8PMo1lNsQlPEObuO4gzGvBctC07hk+vOtG1QMCAJ8oJimPZaj5yQ+Sq+b6sIAVqIz0LAfs49HJYfRBVY4aT+XXL8AgkjFXlAL7XU7i64fSD/GXTvml9SRPbjmU86Uxkukv4PhD468zZ4E7vC8v2VTYnJqN3OOJ2wcemPxtZi7ei8bZIcdP8vEIo3z5z+iIDXw4gWKEtt22jKeQnu6MAQv7fQlZ5cCX1iuvyVT7nli8q3c2vdAZr4G5z/7/GszN/yne05U4Z9n7bM+RB1CWbv1JxXjpnk6FIsAnfFUd8Ybzw=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    all_branches: true
#The following is required to compile JavaFX	
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
